apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cool-app
  name: cool-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cool-app
  serviceName: cool-app
  template:
    metadata:
      labels:
        app: cool-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - cool-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - command:
            - sh
            - -c
            - executablefile --process_number_that_uses_statefulset_suffix $(expr $(hostname | grep -o "[[:digit:]]*$"))
          image: us.gcr.io/host/cool-app
          name: cool-app
